<?php
/**
 * Typesense plugin for Craft CMS 5.x
 *
 * Craft Plugin that synchronises with Typesense
 *
 * @link      https://craft-pulse.com
 * @copyright Copyright (c) 2026 CraftPulse
 */

namespace craftpulse\typesense\services;

use craft\base\Component;
use craftpulse\typesense\builders\Collection;
use craftpulse\typesense\TypesenseCollectionIndex;
use ReflectionFunction;
use Throwable;

/**
 * Fluent config generator.
 *
 * Emits a fluent config file from a legacy TypesenseCollectionIndex (the
 * `config/migrate` path) or from a registry Collection (the `config/export`
 * reverse-migrate path). The schema is emitted deterministically; the legacy
 * resolver closure is copied verbatim through reflection with a review marker.
 * A generated collection round-trips: run back through the registry it produces
 * the same runtime schema map.
 *
 * @author    CraftPulse
 * @package   Typesense
 * @since     5.9.0
 */
class ConfigGenerator extends Component
{
    // Public Methods
    // =========================================================================

    /**
     * Generates a full config file for a set of collection expressions.
     *
     * @param array<int, string> $expressions
     * @return string
     * @author CraftPulse
     */
    public function file(array $expressions): string
    {
        $collections = implode(",\n\n", array_map(
            fn(string $expression): string => $this->_indent($expression, 8),
            $expressions,
        ));

        return <<<PHP
<?php
/**
 * Typesense collections config, generated by craft typesense/config/migrate.
 *
 * Review the elementQuery and transform closures marked REVIEW below: the schema
 * is generated deterministically, but query criteria and resolver bodies should
 * be verified against your original config.
 */

use craft\\elements\\Entry;
use craftpulse\\typesense\\builders\\Collection;
use craftpulse\\typesense\\builders\\Field;
use craftpulse\\typesense\\enums\\MultisiteStrategy;

return [
    'collections' => [
{$collections},
    ],
];

PHP;
    }

    /**
     * Generates the fluent expression for a legacy collection index.
     *
     * @param TypesenseCollectionIndex $legacy
     * @return string
     * @author CraftPulse
     */
    public function fromLegacy(TypesenseCollectionIndex $legacy): string
    {
        $lines = [];
        $lines[] = "Collection::make('{$legacy->indexName}')";
        $lines[] = '    ->elementType(' . $this->_shortClass($legacy->elementType) . '::class)';
        $lines[] = '    ->multisite(MultisiteStrategy::SharedWithSiteFilter)';
        $lines[] = '    ->fields(';

        foreach ($legacy->schema['fields'] ?? [] as $field) {
            $lines[] = '        ' . $this->_fieldExpression($field) . ',';
        }

        $lines[] = '    )';

        if (isset($legacy->schema['default_sorting_field'])) {
            $lines[] = "    ->defaultSortingField('{$legacy->schema['default_sorting_field']}')";
        }

        $lines[] = '    ' . $this->_elementQueryExpression($legacy->section);

        $resolver = $legacy->schema['resolver'] ?? $legacy->resolver;

        if (is_callable($resolver)) {
            $lines[] = '    ' . $this->_transformExpression($resolver);
        }

        return implode("\n", $lines);
    }

    /**
     * Generates the fluent expression for a registry Collection (reverse migrate).
     *
     * @param Collection $collection
     * @return string
     * @author CraftPulse
     */
    public function fromCollection(Collection $collection): string
    {
        $lines = [];
        $lines[] = "Collection::make('{$collection->getName()}')";
        $lines[] = '    ->elementType(' . $this->_shortClass($collection->getElementType()) . '::class)';
        $lines[] = '    ->multisite(MultisiteStrategy::' . $collection->getMultisiteStrategy()->name . ')';
        $lines[] = '    ->fields(';

        foreach ($collection->getFields() as $field) {
            $lines[] = '        ' . $this->_fieldExpression($field->toArray()) . ',';
        }

        $lines[] = '    )';

        foreach ($collection->getMapping() as $mapping) {
            $lines[] = '    // REVIEW: mapping ' . $mapping->documentKey . ' => ' . var_export($mapping->toArray(), true);
        }

        $lines[] = '    // REVIEW: add your ->elementQuery() and ->transform() closures.';

        return implode("\n", $lines);
    }

    // Private Methods
    // =========================================================================

    /**
     * Renders a Field builder expression from a field schema array.
     *
     * @param array<string, mixed> $field
     * @return string
     * @author CraftPulse
     */
    private function _fieldExpression(array $field): string
    {
        $name = $field['name'] ?? '';
        $type = $field['type'] ?? 'string';
        $expression = "Field::make('{$name}', '{$type}')";

        $booleanMethods = [
            'facet' => 'facet',
            'optional' => 'optional',
            'infix' => 'infix',
            'stem' => 'stem',
            'sort' => 'sort',
            'range_index' => 'rangeIndex',
        ];

        foreach ($field as $key => $value) {
            if (in_array($key, ['name', 'type'], true)) {
                continue;
            }

            if (isset($booleanMethods[$key]) && is_bool($value)) {
                $expression .= $value ? "->{$booleanMethods[$key]}()" : "->{$booleanMethods[$key]}(false)";
                continue;
            }

            if (in_array($key, ['index', 'store'], true)) {
                $expression .= "->{$key}(" . var_export((bool)$value, true) . ')';
                continue;
            }

            $expression .= "->raw('{$key}', " . var_export($value, true) . ')';
        }

        return $expression;
    }

    /**
     * Renders the elementQuery expression from a legacy "section.entryType" handle.
     *
     * @param mixed $section
     * @return string
     * @author CraftPulse
     */
    private function _elementQueryExpression(mixed $section): string
    {
        if (!is_string($section) || $section === '') {
            return '->elementQuery(fn($query) => $query) // REVIEW: set your query criteria';
        }

        [$sectionHandle, $entryType] = array_pad(explode('.', $section, 2), 2, null);
        $query = "\$query->section('{$sectionHandle}')";

        if ($entryType !== null && $entryType !== '') {
            $query .= "->type('{$entryType}')";
        }

        return "->elementQuery(fn(\$query) => {$query}) // REVIEW: verify criteria matches your legacy config";
    }

    /**
     * Renders the transform expression, copying the resolver source verbatim.
     *
     * @param callable $resolver
     * @return string
     * @author CraftPulse
     */
    private function _transformExpression(callable $resolver): string
    {
        $source = $this->_resolverSource($resolver);

        if ($source === null) {
            return '->transform(fn($element, $registerDependency) => [/* REVIEW: copy your resolver body */])';
        }

        return "// REVIEW: resolver copied verbatim from the legacy config; verify it\n    ->transform({$source})";
    }

    /**
     * Extracts a resolver closure's source verbatim via reflection, or null.
     *
     * @param callable $resolver
     * @return string|null
     * @author CraftPulse
     */
    private function _resolverSource(callable $resolver): ?string
    {
        if (!($resolver instanceof \Closure)) {
            return null;
        }

        try {
            $reflection = new ReflectionFunction($resolver);
            $file = $reflection->getFileName();
            $start = $reflection->getStartLine();
            $end = $reflection->getEndLine();

            if ($file === false || $start === false || $end === false) {
                return null;
            }

            $source = implode('', array_slice(file($file) ?: [], $start - 1, $end - $start + 1));
            $offset = $this->_functionOffset($source);

            if ($offset === null) {
                return null;
            }

            return rtrim(trim(substr($source, $offset)), ",;");
        } catch (Throwable) {
            return null;
        }
    }

    /**
     * Finds the offset of the closure keyword (`function` or `fn`) in a source slice.
     *
     * @param string $source
     * @return int|null
     * @author CraftPulse
     */
    private function _functionOffset(string $source): ?int
    {
        $candidates = [];

        foreach (['static function', 'function', 'static fn', 'fn'] as $keyword) {
            $position = strpos($source, $keyword);

            if ($position !== false) {
                $candidates[] = $position;
            }
        }

        return $candidates === [] ? null : min($candidates);
    }

    /**
     * Returns the short class name for a fully-qualified class.
     *
     * @param string $class
     * @return string
     * @author CraftPulse
     */
    private function _shortClass(string $class): string
    {
        $parts = explode('\\', $class);

        return end($parts);
    }

    /**
     * Indents every line of an expression by the given number of spaces.
     *
     * @param string $expression
     * @param int $spaces
     * @return string
     * @author CraftPulse
     */
    private function _indent(string $expression, int $spaces): string
    {
        $pad = str_repeat(' ', $spaces);

        return $pad . implode("\n" . $pad, explode("\n", $expression));
    }
}
